My portifolio/Models/Cell.cs
using System.ComponentModel.DataAnnotations;


namespace Exercicios.Models
{

    public class Cell
    {

        [Display(Name = "Conversor Cell")]
        [Required(ErrorMessage = "Informe a temperatura")]
        public double TemperaturaC { get; set;}


        [Display(Name = "Conversor Fehrenheits")]
        public double TemperaturaF { get => Calcular(); } 

        private double Calcular(){
            return  (TemperaturaC - 32) * 5 / 9;
        }
    }

}

My portifolio/Models/ErrorViewModel.cs
namespace Exercicios.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

My portifolio/Models/Partida.cs
using System.ComponentModel.DataAnnotations;

namespace Exercicios.Models
{
    public class Partida
    {
        [Display(Name = "Nome do Time 1")]
        [Required(ErrorMessage = "Informe o Nome do Time")]
        [StringLength(30, ErrorMessage = "O Nome do Time deve possuir no máximo 30 caracteres")]
        public string Time1 { get; set; } = string.Empty;

        [Display(Name = "Gols do Time 1")]
        [Required(ErrorMessage = "Informe o Número de Gols do Time 1")]
        [RegularExpression(@"[0-9]*$", ErrorMessage = "Informe um valor válido!")]
        public int GolsTime1 { get; set; } = 0;

        [Display(Name = "Nome do Time 2")]
        [Required(ErrorMessage = "Informe o Nome do Time 2")]
        [StringLength(30, ErrorMessage = "O Nome do Time 2 deve possuir no máximo 30 caracteres")]
        public string Time2 { get; set; } = string.Empty;

        [Display(Name = "Gols do Time 2")]
        [Required(ErrorMessage = "Informe o Número de Gols do Time 2")]
        [RegularExpression(@"[0-9]*$", ErrorMessage = "Informe um valor válido!")]
        public int GolsTime2 { get; set; } = 0;

        public string Resultado
        {
            get
            {
                 if (GolsTime1 > GolsTime2) 
                 return  $"Vitória do {Time1}"; 
                else
                    if ( GolsTime2 > GolsTime1) 
                        return $"Vitória do {Time2}";
                    else 
                        return $"Empate entre {Time1} e {Time2}";                                  
            }
            
        }
    }
}

My portifolio/Models/Prestacao.cs
using System.ComponentModel.DataAnnotations;

namespace Exercicios.Models
{
    public class Prestacao
    {
        [Display(Name = "Valor da Prestação")]
        [Required(ErrorMessage = "Informe o Valor da Prestação")]
        [RegularExpression(@"^\d+,?\d{0,2}$", ErrorMessage = "Informe um valor válido!")]
        public double Valor { get; set; }
        
        [Display(Name = "Taxa de Juros")]
        [Required(ErrorMessage = "Informe a Taxa de Juros")]
        [RegularExpression(@"^\d+.?\d{0,2}$", ErrorMessage = "Informe um valor válido!")]
        public double TaxaJuros { get; set; }

        [Display(Name = "Dias em Atraso")]
        [Required(ErrorMessage = "Informe o Número de Dias em Atraso")]
        [RegularExpression(@"[0-9]*$", ErrorMessage = "Informe um valor válido!")]
        public int DiasEmAtraso { get; set; }

        [Display(Name = "Prestação com Juros")]
        [DisplayFormat(DataFormatString="{0:#.##}")]
        public double PrestacaoComJuros { get => Calcular(); }


      

        private double Calcular(){
            return Valor + (Valor * (TaxaJuros / 100) * DiasEmAtraso);
        }

    }
}

My portifolio/Controllers/CondicionaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exercicios.Models;
using Microsoft.AspNetCore.Mvc;

namespace Exercicios.Controllers
{
    public class CondicionaisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CondicionalIf()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CondicionalIf(Partida partida)
        {
            return View(partida);
        }

        public IActionResult CondicionalSwitch()
        {
            return View();
        }
    }
}

My portifolio/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Exercicios.Models;

namespace Exercicios.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult SobreMim()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

My portifolio/Controllers/MatematicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exercicios.Models;
using Microsoft.AspNetCore.Mvc;

namespace Exercicios.Controllers
{
    public class MatematicosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Exercicio1()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio1(string Nome, double Nota1, double Nota2, double Nota3)
        {
            double media = (Nota1 + Nota2 + Nota3) / 3.0;
            ViewData["Resultado"] = $"O aluno {Nome} obteve média {media:N2}";
            return View();
        }

        [HttpGet]
        public IActionResult Exercicio2()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio2(Prestacao prestacao)
        {
            return View(prestacao);
        }
        
        [HttpGet]
        public IActionResult Exercicio3()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio3(Cell cell)
        {
            return View(cell);
        }


    }
}

My portifolio/Controllers/RepeticaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Exercicios.Controllers
{
    public class RepeticaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

My portifolio/Views/Condicionais/CondicionalIf.cshtml
@model Partida
@{
    ViewData["Title"] = "CondicionalIf";
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Condições If</h1>
        <p class="font-weight-light fs-2">Partida</p>
    </div>
</section>

<div class="container mt-4">
    <div class="row justify-content-md-center">
        <form method="post" class="col-lg-8 col-md-12">
            <p class="mb-4">
                Criar um formulário para ler o nome de 2 times e o número de gols marcados na partida 
                (para cada time). Escrever o nome do vencedor. Caso não haja vencedor deverá ser 
                impressa a palavra 'EMPATE'.
            </p>
            <div class="col-12 py-3">
                <p class="fs-1 text-center bg-dark text-white">@(Model != null ? Model.Resultado : "")</p>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <label asp-for="Time1" class="form-label"></label>
                    <input asp-for="Time1" class="form-control">
                    <span asp-validation-for="Time1" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="GolsTime1" class="form-label"></label>
                    <input asp-for="GolsTime1" class="form-control">
                    <span asp-validation-for="GolsTime1" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <label asp-for="Time2" class="form-label"></label>
                    <input asp-for="Time2" class="form-control">
                    <span asp-validation-for="Time2" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="GolsTime2" class="form-label"></label>
                    <input asp-for="GolsTime2" class="form-control">
                    <span asp-validation-for="GolsTime2" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Calcular</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

My portifolio/Views/Condicionais/CondicionalSwitch.cshtml
@{
    ViewData["Title"] = "CondicionalSwitch";
}

<h1>CondicionalSwitch</h1>

My portifolio/Views/Condicionais/Index.cshtml
@{
    ViewData["Title"] = "Estruturas Condicionais";
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Estruturas Condicionais</h1>
        <p class="font-weight-light">Se e Escolha</p>
    </div>
</section>

<div class="container mt-5">
    <div class="row justify-content-md-center">
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card" style="padding:0;">
                <img src="@Url.Content("~/img/partida.jpg")" class="card-img-top" alt="Condicional IF - Partida">
                <div class="card-body">
                    <h5 class="card-title text-center">Futebol</h5>
                    <p class="card-text">Dados os pontos de uma partida de futebol, informe o Time vencedor.
                    </p>
                    <a asp-action="CondicionalIf" class="btn btn-primary">Abrir</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card" style="padding:0">
                <img src="@Url.Content("~/img/imc.jpg")" class="card-img-top" alt="Condicional IF">
                <div class="card-body">
                    <h5 class="card-title text-center">IMC</h5>
                    <p class="card-text">Calcular o IMC de uma pessoa e informar-la sua situação de saúde (peso).
                    </p>
                    <a asp-action="CondicionalSwitch" class="btn btn-primary">Abrir</a>
                </div>
            </div>
        </div>
    </div>
</div>

My portifolio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="fundo">
    <div class="container mt-5">
        <div class="text-center">
            <h1 class="display-4 mb-5">Bem-vindo ao Projeto Exercícios</h1>
            <p class="fs-3">Projeto totalmente desenvolvido em sala de aula, com o intuito de aprendermos a desenvolver o modelo MVC do C#.</p>
        </div>
    </div>
<div>

My portifolio/Views/Home/SobreMim.cshtml
@{
    ViewData["Title"] = "Sobre Mim";
}

<section class="bg-dark text-white text-center pb-3">
    <div class="container d-flex align-items-center flex-column">
        <img class="mb-5" src="https://avatars.githubusercontent.com/u/99850729?v=4" alt="Avatar" width="150"
            style="border-radius:50%;" />
        <h1 class="text-uppercase mb-0">Emanuel Santos Souza de Jesus</h1>
        <p class="font-weight-light mb-0">Estudante - Programador</p>
    </div>
</section>

<section class="page-section text-dark mb-5 mt-5">
    <div class="container">
        <div class="d-flex justify-content-evenly">
            <div class="col-lg-4">
                <h2 class="page-section-heading d-inline-block ">SOBRE MIM</h2>
                <p class="lead">Olá, me chamo Emanuel, estou no contínuo processo de desenvolvimento pessoal para melhorar
                    minhas habilidades com programação e design. Sou Programador Full Stack e trabalho com várias
                    linguagens, como por exemplo: HTML, CSS, Javascript, MySQL, C#, Delphi, Iônico. Além disso tenho
                    conhecimento no Sistemas Operacional Linux, consigo me virar no prompt do Linux, também desenvolvo
                    com alguns frameworks com Bootstrap e Query, atualmente tenho 17 e estou cursando Desenvolvimento de
                    Sistemas e Esse é apenas o começo da minha carreira.</p>
            </div>
            <div class="col-lg-4">
                <h2 class="page-section-heading d-inline-block ">ABOUT ME</h2>
                <p class="lead">"Hello, my name is Emanuel, I am in the continuous process of personal development to improve
                    my programming and design skills. I am a Full Stack Programmer and work with several
                    languages, such as: HTML, CSS, Javascript, MySQL, C#, Delphi, Ionic. In addition, I have
                    knowledge in Linux Operating Systems, I can turn on the Linux prompt, I also develop
                    with some frameworks with Bootstrap and Query, I'm currently 17 and I'm studying Development of
                    Systems and That's just the beginning of my career.</p>
            </div>
        </div>
    </div>
</section>

My portifolio/Views/Matematicos/Exercicio1.cshtml
@{
    ViewData["Title"] = "Operadores Matemáticos";
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Operadores Matemáticos</h1>
        <p class="font-weight-light fs-2">Média Escolar</p>
    </div>
</section>

<div class="container mt-4">
    <div class="row justify-content-center">
        <form method="post" class="col-lg-8 col-md-12">
            <p class="mb-4">
                Leia o nome de um aluno e três notas obtidas durante o semestre, ao final mostre o 
                nome do aluno e a média aritmética das notas. 
            </p>
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome do Aluno:</label>
                <input type="text" class="form-control" id="Nome" name="Nome">
            </div>
            <div class="row mb-4">
                <div class="col">
                    <label for="Nota1" class="form-label">Nota 1</label>
                    <input type="text" class="form-control" id="Nota1" name="Nota1">
                </div>
                <div class="col">
                    <label for="Nota2" class="form-label">Nota 2</label>
                    <input type="text" class="form-control" id="Nota2" name="Nota2">
                </div>
                <div class="col">
                    <label for="Nota3" class="form-label">Nota 3</label>
                    <input type="text" class="form-control" id="Nota3" name="Nota3">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Calcular</button>
            <p class="fs-2 text-center">@ViewData["Resultado"]</p>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

My portifolio/Views/Matematicos/Exercicio2.cshtml
@model Prestacao
@{
    ViewData["Title"] = "Operadores Matemáticos";
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Operadores Matemáticos</h1>
        <p class="font-weight-light fs-2">Prestação com Juros</p>
    </div>
</section>

<div class="container mt-4">
    <div class="row justify-content-md-center">
        <form method="post" class="col-lg-8 col-md-12">
            <p class="mb-4">
                Analisando a fórmula "Prestação = valor + (valor * (taxa/100) * tempo)", crie um algoritmo para efetuar
                o cálculo do valor de uma prestação em atraso. (Você deverá ler o VALOR da prestação, a TAXA de juros
                imposta pelo banco, e o número de dias em ATRASO.
            </p>
            <div class="row mb-4">
                <div class="col">
                    <label asp-for="Valor" class="form-label"></label>
                    <input asp-for="Valor" class="form-control">
                    <span asp-validation-for="Valor" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="TaxaJuros" class="form-label"></label>
                    <input asp-for="TaxaJuros" class="form-control">
                    <span asp-validation-for="TaxaJuros" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <label asp-for="DiasEmAtraso" class="form-label"></label>
                    <input asp-for="DiasEmAtraso" class="form-control">
                    <span asp-validation-for="DiasEmAtraso" class="text-danger"></span>
                </div>
                <div class="col">
                    <label asp-for="PrestacaoComJuros" class="form-label"></label>
                    <input asp-for="PrestacaoComJuros" class="form-control" disabled>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Calcular</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

My portifolio/Views/Matematicos/Exercicio3.cshtml
@model Cell
@{
    ViewData["Title"] = "Conversor Temperatura";    
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Conversão de Fahrenheit em Celsius</h1>
    </div>
</section>


<div class="container mt-4">
    <div class="row justify-content-md-center">
        <form method="post" class="col-lg-8 col-md-12">
            <p class="mb-4">
                
            </p>
            <div class="row mb-4">
                <div class="col">
                    <label asp-for="TemperaturaC" class="form-label"></label>
                    <input asp-for="TemperaturaC" class="form-control">
                    <span asp-validation-for="TemperaturaC" class="text-danger"></span>
                </div>
            
                <div class="col">
                    <label asp-for="TemperaturaF" class="form-label"></label>
                    <input asp-for="TemperaturaF" class="form-control" disabled>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Calcular</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

My portifolio/Views/Matematicos/Index.cshtml
@{
    ViewData["Title"] = "Operadores Matemáticos";
}

<section class="bg-dark text-white text-center py-3">
    <div class="container d-flex align-items-center flex-column">
        <h1 class="text-uppercase mb-3">Operadores Matemáticos</h1>
        <p class="font-weight-light"> + - * / </p>
    </div>
</section>

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
            <div class="card" style="padding:0;">
                <img src="~/img/media.jpg" class="card-img-top" alt="Média Escolar" height="210">
                <div class="card-body">
                    <h5 class="card-title text-center">Escola</h5>
                    <p class="card-text">Média aritméticas de 3 notas obtidas por um aluno em um bimestre.
                    </p>
                    <a asp-controller="Matematicos" asp-action="Exercicio1" class="btn btn-primary">Abrir</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12  mb-4">
            <div class="card" style="padding:0">
                <img src="@Url.Content("~/img/juros.jpg")" class="card-img-top" alt="Prestação com Juros" height="210">
                <div class="card-body">
                    <h5 class="card-title text-center">Prestaçã com Juros</h5>
                    <p class="card-text">Calcular o valor de uma prestação acrescida de juros por atraso.
                    </p>
                    <a asp-controller="Matematicos" asp-action="Exercicio2" class="btn btn-primary">Abrir</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12  mb-4">
            <div class="card" style="padding:0">
                <img src="@Url.Content("~/img/expressao.jpg")" class="card-img-top" alt="Expressão Matemática" height="210">
                <div class="card-body">
                    <h5 class="card-title text-center">Expressão Matemática</h5>
                    <p class="card-text">Dados 3 números inteiros positivos, calcule a expressão dada.
                    </p>
                    <a asp-controller="Matematicos" asp-action="Exercicio3" class="btn btn-primary">Abrir</a>
                </div>
            </div>
        </div>
    </div>
</div>